[package]
name = "echo-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.*"
hyper = {version = "*", features = ["full"]}
tokio = {version = "*", features = ["full"]}
serde_json = "1.*"